### ISSUE TITLE
std maps with missing entries

### ISSUE THREAD

**Issue by v-lopez** [asherikov/ariles#3]
Hi @asherikov,

Glad to see ariles is getting even more new features.
I've got an issue with reading a class with missing entries that is within a map.

```c++
struct SubstateParams : public ariles::RelaxedConfigurableBase
{
  #define ARILES_SECTION_ID "SubstateParams"
  #define ARILES_ENTRIES \
  ARILES_ENTRY(type) \
  ARILES_ENTRY(remappings)
  #include ARILES_INITIALIZE

  std::string type;
  std::map<std::string, std::string> remappings;
};

struct StateMachineParams : public ariles::RelaxedConfigurableBase
{
  #define ARILES_SECTION_ID "StateMachineParams"
  #define ARILES_ENTRIES \
  ARILES_ENTRY(substates)
  #include ARILES_INITIALIZE

  std::map<std::string, SubstateParams> substates;
};
```

I'm loading this:
```yaml
MAIN_SM:
    substates:
        STATE_1:
            type: "TestState"
            remappings: {"a":"a"}
```

If either type or remappings is missing, I get the following error:
> C++ exception with description "In operator()() // Failed to parse entry <test_sm/MAIN_SM> ||  In operator()() // Failed to parse entry <substates> ||  In operator()() // Failed to parse entry <STATE_1> ||  In operator()() // Configuration file does not contain entry 'type'." thrown in the test body.

It looks to me like it might be related to this:
https://github.com/asherikov/ariles/blob/master/include/ariles/adapters/std_map.h#L64

I've removed it and it works, but I don't know why it was there in the first place, so I'd like to get some insights on this.

Thanks for your help and take care these days.

**Comment by asherikov** [comment]
Hi, thanks for the feedback, I'll try to check this during the weekend.

**Comment by asherikov** [comment]
Should be fixed in this branch -> https://github.com/asherikov/ariles/pull/4, let me know if it works.

**Comment by asherikov** [comment]
ROS package is in `pkg_ros_test` branch.

**Comment by v-lopez** [comment]
Besides the warning that I mentioned in the merge request, this fixes the issue I had.

Thanks a lot

**Comment by asherikov** [comment]
Ok, I'll merge the patch and deal with the warnings later.
BTW, you may be interested in this -> https://github.com/asherikov/ariles/blob/master/bridges/array/ariles/visitors/array/writer.h, basically it dumps ariles classes into a list of <string, double> pairs, works well for time-series data, such as collected by pal_statistics.

**Comment by v-lopez** [comment]
>  BTW, you may be interested in this -> https://github.com/asherikov/ariles/blob/master/bridges/array/ariles/visitors/array/writer.h, basically it dumps ariles classes into a list of <string, double> pairs, works well for time-series data, such as collected by pal_statistics.

Thanks that looks very interesting. 

I am afraid some behavior has changed with the last fixes. I believe that code that used non-sloppy maps before will not work now.

For instance, these parameters: https://github.com/pal-robotics/tiago_robot/blob/kinetic-devel/tiago_description/config/collision/collision_parameters.yaml

Will not be loaded by this class:
```
class CollisionModelParameters : public ariles::ConfigurableBase
{
#define ARILES_SECTION_ID "collision_model_parameters"
#define ARILES_ENTRIES                                                                   \
  ARILES_ENTRY_(padding)                                                                 \
  ARILES_ENTRY_(links_with_padding)                                                      \
  ARILES_ENTRY_(blacklist)
#include ARILES_INITIALIZE

public:
  double padding_;
  std::vector<std::string> links_with_padding_;
  std::map<std::string, std::vector<std::pair<std::string, std::string> > > blacklist_;
public:
  CollisionModelParameters()
  {
    setDefaults();
  }
  void setDefaults()
  {
    padding_ = 0.0;
    links_with_padding_.clear();
    blacklist_.clear();
  }
};
```

The error is:
>   what():  In start() // Failed to parse entry </foo/collision_model_parameters> ||  In operator()() // Failed to parse entry <blacklist> ||  In operator()() // Failed to parse entry <default> ||  In apply_read() // Wrong number of pair entries for a sloppy pair.

Thanks for all your help

**Comment by asherikov** [comment]
Ok, I'll check

**Comment by asherikov** [comment]
You are mixing sloppy map with non-sloppy pairs, in order to parse this file you have to set `ariles::ConfigurableFlags::SLOPPY_MAPS_IF_SUPPORTED` and unset `ariles::ConfigurableFlags::SLOPPY_PAIRS_IF_SUPPORTED`, or reformat the file.

**Comment by asherikov** [comment]
BTW, warnings should be fixed in the master

**Comment by v-lopez** [comment]
Awesome, thanks for the help response.

I'll see about the sloppy/non-sloppy issue.
