### ISSUE TITLE
Changed inheritance behaviour

### ISSUE THREAD

**Issue by v-lopez** [asherikov/ariles#9]
Hi,

In an older version of ariles, I was able to do this:
```
struct ArilesPoint : public Eigen::Vector3d, public ariles::ConfigurableBase
{
  geometry_msgs::Point getMsg() const
  {
    geometry_msgs::Point p;
   //convert *this to p 
    return p;
  }

#define ARILES_SECTION_ID "ArilesPoint"
#define ARILES_CONSTRUCTOR ArilesPoint
#define ARILES_ENTRIES
#include ARILES_INITIALIZE
};
```

As a simple way of reading vectors and converting them to ROS msgs. Right now the `Eigen::Vector3d` components are not being set to anything when reading from the ROS param server.

And I read it from this:
```
  ros::NodeHandle nh;
  ArilesPoint point;
  point.readConfig<ariles::ros>(nh, "point");
```

And in the param server:
```
point: [1,2,3]
```

Is this something supported, or the entries should always be a member of the class and be within a namespace?
```
point:
  point: [1,2,3]
```

**Comment by asherikov** [comment]
1. If it was working then it was a bug ;), the class has no 'ariles' members and shouldn't read anything.
2. I don't think `point: [1,2,3]` is possible, I'll try a few things in the evening.

**Comment by asherikov** [comment]
You can achieve something similar if `ArilesPoint` is not a child of `ariles::ConfigurableBase` and is a member of another ariles class, e.g., https://github.com/asherikov/ariles/blob/as_eigen_wrapper/tests/api_v1/types/eigen_wrapper.h:
```
ArilesPoint:
  point: [0, 0, 0]
```

I doubt that the behavior you want was possible in older versions. I can double check, if you can provide the exact ariles version and a working example.

**Comment by v-lopez** [comment]
Awesome, I'll give it a try tomorrow.

The previous code was working with the Jan'15th 2019 version you updated from this repo.

But  not much code is uses this ArilesPoint class, so I can fix it to work with this behavior. Thanks for the quick response.
